<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sensio\Bundle\FrameworkExtraBundle\Configuration;

use Symfony\Component\Routing\Annotation\Route as BaseRoute;

/**
 * @author Kris Wallsmith <kris@symfony.com>
 * @Annotation
 */
class Route extends BaseRoute
{
    private $service;

    public function setService($service)
    {
        // avoid a BC notice in case of @Route(service="") with sf ^2.7
        if (null === $this->getPath()) {
            $this->setPath('');
        }
        $this->service = $service;
    }

    public function getService()
    {
        return $this->service;
    }

    /**
     * @param $requirements
     */
    public function setRequirements($requirements)
    {
        if (is_array($requirements)) {
            foreach ($requirements as $key => $value) {
                // Replace '\uuid4' with the proper regex
                if ($value === '\uuid4') {
                    $requirements[$key] = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}';
                }
            }
        }

        parent::setRequirements($requirements); // TODO: Change the autogenerated stub
    }


    /**
     * Multiple route annotations are allowed.
     *
     * @return bool
     *
     * @see ConfigurationInterface
     */
    public function allowArray()
    {
        return true;
    }
}
